export {ComponentBase} from './ComponentBase';
export type {ComponentBaseProps as ComponentProps} from './ComponentBase';
export {ComponentISBN as DetailTableItemISBN} from './ItemISBN';
export type {ComponentISBNProps as DetailTableItemISBNProps} from './ItemISBN';
export {ComponentLanguages as DetailTableItemLanguages} from './ItemLanguages';
export type {ComponentLanguagesProps as DetailTableItemLanguagesProps} from './ItemLanguages';
export {ComponentPages as DetailTableItemPages} from './ItemPages';
export type {ComponentPagesProps as DetailTableItemPagesProps} from './ItemPages';
export {ComponentPublishedAt as DetailTableItemPublishedAt} from './ItemPublishedAt';
export type {ComponentPublishedAtProps as DetailTableItemPublishedAtProps} from './ItemPublishedAt';
export {ComponentPublishers as DetailTableItemPublishers} from './ItemPublishers';
export type {ComponentPublishersProps as DetailTableItemPublishersProps} from './ItemPublishers';
