export {ComponentBase} from './ComponentBase';
export type {ComponentBaseProps as ComponentProps} from './ComponentBase';
export {Component as DetailTableItemISBN} from './ItemISBN';
export type {ComponentProps as DetailTableItemISBNProps} from './ItemISBN';
export {Component as DetailTableItemLanguages} from './ItemLanguages';
export type {ComponentProps as DetailTableItemLanguagesProps} from './ItemLanguages';
export {Component as DetailTableItemPages} from './ItemPages';
export type {ComponentProps as DetailTableItemPagesProps} from './ItemPages';
export {Component as DetailTableItemPublishedAt} from './ItemPublishedAt';
export type {ComponentProps as DetailTableItemPublishedAtProps} from './ItemPublishedAt';
export {Component as DetailTableItemPublishers} from './ItemPublishers';
export type {ComponentProps as DetailTableItemPublishersProps} from './ItemPublishers';
