export {BaseComponent} from './BaseComponent';
export type {BaseComponentProps} from './BaseComponent';
export {Component as Left} from './ButtonLeft';
export type {ComponentProps as LeftProps} from './ButtonLeft';
export {Component as Leftest} from './ButtonLeftest';
export type {ComponentProps as LeftestProps} from './ButtonLeftest';
export {Component as Right} from './ButtonRight';
export type {ComponentProps as RightProps} from './ButtonRight';
export {Component as Rightest} from './ButtonRightest';
export type {ComponentProps as RightestProps} from './ButtonRightest';
