version: 2.1

orbs:
  node: circleci/node@4.1.0
  docker: circleci/docker@1.5.0
  codecov: codecov/codecov@1.1.3

jobs:
  lint-prettier:
    docker:
      - image: circleci/node:14.15.3
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn run lint:prettier

  lint-eslint:
    docker:
      - image: circleci/node:14.15.3
    parameters:
      schema:
        type: string
    environment:
      GRAPHQL_API_SCHEMA: << parameters.schema >>
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - restore_cache:
          key: eslint-{{ .Branch }}
      - run: yarn run codegen
      - run:
          command: |
            yarn run lint:eslint --format junit --output-file ./junit/eslint.xml
      - save_cache:
          key: eslint-{{ .Branch }}
          paths:
            - .eslintcache
      - store_test_results:
          path: ./junit

  lint-stylelint:
    docker:
      - image: circleci/node:14.15.3
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - restore_cache:
          key: stylelint-{{ .Branch }}
      - run: yarn run lint:stylelint
      - save_cache:
          key: stylelint-{{ .Branch }}
          paths:
            - .stylelintcache

  ts-check:
    docker:
      - image: circleci/node:14.15.3
    parameters:
      schema:
        type: string
    environment:
      GRAPHQL_API_SCHEMA: << parameters.schema >>
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn run codegen
      - run: yarn run ts-check

workflows:
  version: 2
  develop:
    jobs:
      - ts-check:
          schema: ./schema.graphql
      - lint-eslint:
          schema: ./schema.graphql
      - lint-prettier
      - lint-stylelint
